config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"
  resources :tweets, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(text: params[:text])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/create.html.erb
<h1>投稿が完了しました</h1>

<%= link_to "トップへ戻る", root_path %>

app/views/tweets/index.html.erb
<h1>Welcome First App!</h1>

<%= link_to "投稿ページ", "tweets/new" %>

<% @tweets.each do |tweet| %>
  <div>
    <%= tweet.text %>
    <%= tweet.created_at %>
  </div>  
<% end %>

app/views/tweets/new.html.erb
<h1>新規投稿画面</h1>

<%= form_with url: tweets_path, method: :post, local: true do |form| %>
  <%= form.text_field :text %>
  <%= form.submit '投稿する' %>
<% end %>